### ISSUE TITLE
Standardize format of `*_version` inputs

### ISSUE THREAD

**Issue by hknutsen** [equinor/ops-actions#229]
Standardize the format of `*_version` inputs to `x.y.z`.

Any time a `*_version` input is used, implement relevant logic to use latest patch version of `x.y.z`.

For example, in `terraform.yml`, an input `terraform_version` is passed to `hashicorp/setup-terraform` to setup Terraform. This action supports the syntax `~x.y.z` to use the latest patch version, thus our workflow should call this actions like this:

```yaml
- name: Setup Terraform
  uses: hashicorp/setup-terraform@v2
  with:
    terraform_version: "~${{ inputs.terraform_version }}"
```
