### ISSUE TITLE
Standardize archive format

### ISSUE THREAD

**Issue by hknutsen** [equinor/ops-actions#464]
We should standardize the way we create archives for uploading to GitHub Artifacts.

I think a good solution would be tarballs (`.tar`), since all Linux distros ship with the required tooling to both create and extract tarballs.

Create tarball and upload artifact:

```yaml
- name: Checkout
  uses: actions/checkout@v4

- name: Create tarball
  id: tar
  working-directory: ${{ inputs.working_directory }}
  run: |
    tarball="$RUNNER_TEMP/$ARTIFACT_NAME.tar"
    tar -cvf "$tarball" .
    echo "tarball=$tarball" >> "$GITHUB_OUTPUT"

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: ${{ inputs.artifact_name }}
    path: ${{ steps.tar.outputs.tarball }}
```

Workflows that upload artifacts:

- `dotnet`
- `python`
- `terraform` (tarball must be encrypted. Use `gpg`?)

Download artifact and extract tarball:

```yaml
- name: Download artifact
  uses: actions/download-artifact@v4
  with:
    name: ${{ inputs.artifact_name }}

- name: Extract tarball
  run: |
    tarball="$ARTIFACT_NAME.tar"
    tar -xvf "$tarball"
    rm "$tarball"
```

Workflows that download artifacts:

- `azure-function`
- `azure-webapp`
- `terraform` (tarball must be decrypted. Use `gpg`?)

Should create one PR per workflow that is modified.

Could also update `docs/best-practices.md` to recommend creating tarballs before uploading artifacts.
